// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHxvkDbocJA-v6m3w8CFMrzRpjkBCoEc',
    appId: '1:163430220369:web:b915c4c2ddc27ce16a2e70',
    messagingSenderId: '163430220369',
    projectId: 'movie-app-8d907',
    authDomain: 'movie-app-8d907.firebaseapp.com',
    storageBucket: 'movie-app-8d907.appspot.com',
    measurementId: 'G-FPFX431XV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGPsQ5eY4ftrstLOfMtRju991R_jW38A',
    appId: '1:163430220369:android:9bf565c7992317826a2e70',
    messagingSenderId: '163430220369',
    projectId: 'movie-app-8d907',
    storageBucket: 'movie-app-8d907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBML4WyWh3pYH2TF4KJEjF3r_ebvBUJ6Yk',
    appId: '1:163430220369:ios:51c396d9e9d429966a2e70',
    messagingSenderId: '163430220369',
    projectId: 'movie-app-8d907',
    storageBucket: 'movie-app-8d907.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBML4WyWh3pYH2TF4KJEjF3r_ebvBUJ6Yk',
    appId: '1:163430220369:ios:cedd799fa1939f8f6a2e70',
    messagingSenderId: '163430220369',
    projectId: 'movie-app-8d907',
    storageBucket: 'movie-app-8d907.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
